### ISSUE TITLE
Considering Nostr for user authentication

### ISSUE THREAD

**Issue by morrisonbrett** [TrueVote/TrueVote.Api#33]
The [TrueVote white paper](https://truevote.org/TrueVote.pdf) outlines the use of LastPass style account login / password / encryption / recovery.

Since the white paper was written, [Nostr](https://nostr.com) has risen as a nascent protocol that's being rapidly adopted by the Bitcoin community and beyond and is the backbone of many new projects being built.

As part of the development of the TrueVote platform, authentication into the platform is an obviously important and critical piece. This is different from _voter eligibility_. Voter eligibility is a larger topic and out of scope for authentication. Eligibility is the linking of a user's profile with their ability to submit a ballot for a particular election. This is determined by the jurisdiction and voting requirements for the election. That eligibility is _linked_ to their account, and a submitted ballot is only known to the user.

The context of **this** issue is for authentication only.

Using a third party provider such as Auth0, Google, or Facebook is a non-starter as we want to lessen our dependencies on any 3rd party services wherever possible - especially something as critical as user authentication.

User authentication will be used to login to TrueVote and also for role assignment (e.g. Voter, Admin, Election Admin, etc.).

So, the question is, do we build it like LastPass auth model username / master password (of course with 2FA), or custom oAuth, or [PassKeys](https://passkeys.dev), or - consider using Nostr.

### Pros

- Simple, proven private / public key encryption
- User is responsible for storing their private key safely and is something they're becoming more and more comfortable with
- Extensions like Alby can be used or user can enter private key and store it in browser / mobile secure storage (never transmitted to TrueVote)
- VERY easy to implement
- Nostr could end up being **the** decentralized identifier DID the tech world has been looking for. TrueVote can use attestations to prove voter eligibility.

### Cons

- Nostr is not easy enough for everyone yet. BUT - this isn't necessarily a con. For users that don't have a Nostr key pair, TrueVote can make a simple screen to create one. It needs to be simple enough that anyone (e.g. Grandmas) can use it.
- No private key recovery
- Probably need to standup TrueVote Nostr redundant relay(s) for less dependencies on public relays
- Still need to guard against Sybil attacks. How? Rate limiting by IP?

## High-Level Workflow

- Prompt user for public key, private key, email address (Nostr way to ask for email?)
- User must verify email via link sent
- Once email verified, account is usable:
    - Account key can now be used to access API 
    - View / Change account settings
    - View which elections voter is eligible for (this is linked via back-end later e.g voter registration)
    - Vote in sample election
    - View user's submitted ballots using ballot explorer
    - View election results
    - More...

**Comment by morrisonbrett** [comment]
This has now be en implemented. Next up is issuing an API access token for an authenticated Nostr key. The /user/signin endpoint currently returns a placeholder token.

Considering building a microservice for this that the TrueVote.Api would call. This way if we wanted to change auth at some point, we could just implement a new microservice.

Evaluating:

* Microsoft Owin
* Microsoft.Identity.Web
* Generic OAuth
* Very basic JWToken

**Comment by akolaarthurali** [comment]
Great to hear 👍 that the Nostr authentication proposal was implemented and considering a microservice to improve programmability
